openapi: 3.0.0
info:
  description: alex chat adapter API
  version: 0.0.1
  title: alex-chat-adapter
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: GPLv2
    url: 'https://www.gnu.org/licenses/gpl-2.0.en.html'
servers:
  - url: /api/v1
    description: The APIs base path
tags:
  - name: data-source
    description: Data-Source related APIs
paths:
  /message:
    post:
      tags:
        - message
      summary: Intent-input
      description: ''
      operationId: api.message.send
      requestBody:
        description: Message to send
        content:
          application/json:
            schema:
              required:
                - message
              properties:
                message:
                  type: string
                mention_user:
                  type: string
      responses:
        '204':
          description: Success
  /proactive:
    post:
      tags:
        - skill
        - proactive
      summary: Get dynamic information from a monitoring entity (to be called from skill)
      description: ''
      operationId: api.skill.proactive
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/monitorRequestPayload'
      responses:
        '204':
          description: Success

components:
  schemas:
    userId:
      type: string
      format: uuid
      example: 0693d37c-404a-423c-b802-424341ff087b
    monitorRequestPayload:
      required:
        - type
        - payload
      properties:
        type:
          type: string
          example: daily_briefing
        payload:
          type: object

externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
